controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ResetPassword;
use app\models\ContactForm;
use yii\web\UrlManager\Url;
use yii\db\Query;
use yii\db\Command;
use app\models\Emails;
use app\models\Employees;
use app\models\User;
use yii\web\Session;
use app\models\FormRecoverPass;
use app\models\FormResetPass;


class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
					'only' => ['login', 'logout'],
					'rules' => [
                    [
                        'actions' => ['login', 'logout'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
					
					  [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
					
					
					
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
	
	private function randKey($str='', $long=0)
	{
		$key = null;
		$str = str_split($str);
		$start = 0;
		$limit = count($str)-1;
		for($x=0; $x<$long; $x++)
		{
			$key .= $str[rand($start, $limit)];
		}
		return $key;
	}
	
	
	///////////////////////////////////////////////////////////
	public function actionRecoverpass()
 {
  
  $model = new FormRecoverPass();
  
  
  $msg = null;
  
 if ($model->load(Yii::$app->request->post()))
  {
   if ($model->validate())
  {
    
   $table = User::find()->where("email =:email",[":email" => $model-> email]);
    
    //Si el usuario existe
    if ($table->count() == 1)
    {
     
     $session = new Session;
     $session->open();
     
     
     $session["recover"] = $this->randKey("abcdef0123456789", 200);
     $recover = $session["recover"];
     
     
    //$table = User::find()->where("email=:email", [":email" => $model->email])->one();
	//$table = User::find()->where(['email' =>  $model->email])->one();
	$table = User::find()->where("email =:email",[":email" => $model->email])->one();
	 
	 
     $session["id_recover"] = $table->id;    
     
     $verification_code = $this->randKey("abcdef0123456789",8);
     //Columna verification_code
     $table->verification_code = $verification_code;
     $table->save(false);
     
     //שליחה למייל
     $subject = "איפוס סיסמה";
     $body = "<div style='text-align:right;'><h3>,שלום וברכה</h3><p>:בהמשך לתהליך איפוס הסיסמה, קוד האימות הינו  ";
     $body .= "</div><strong>".$verification_code."</strong></p>";
     $body .= "<p><a href='http://prat.webni.co.il/app/web/site/resetpass'>לחץ לאיפוס הסיסמה</a></p>";

     //שליחת מייל
     Yii::$app->mailer->compose()
     ->setTo($model->email)
     ->setFrom(['prat@webni.co.il' => 'prat@webni.co.il' ])
     ->setSubject($subject)
     ->setHtmlBody($body)
     ->send();
     
     //Vaciar el campo del formulario
     $model->email = null;
     
     //Mostrar el mensaje al usuario
     Yii::$app->session->setFlash('successPmail','קוד האימות נשלח בהצלחה לכתובת המייל!');
	 return $this->redirect(['/site/index']);
    }
    else //El usuario no existe
    {
     $msg = "כתובת מייל שגויה!";
    }
   }
   else
   {
    $model->getErrors();
   }
  }
  return $this->render("recoverpass", ["model" => $model, "msg" => $msg]);
 }
 //////////////////////////////////////////////////////////////////////////////////
 public function actionResetpass()
 {
  
  $model = new FormResetPass;
  
  
  $msg = null;
  
  
  $session = new Session;
  $session->open();
  
  //Si no existen las variables de sesión requeridas lo expulsamos a la página de inicio
  if (empty($session["recover"]) || empty($session["id_recover"]))
  {
   return $this->redirect(["site/index"]);
  }
  else
  {
   
   $recover = $session["recover"];
  
   $model->recover = $recover;
   
   $id_recover = $session["id_recover"];
   
  }
  
  
  if ($model->load(Yii::$app->request->post()))
  {
   if ($model->validate())
   {
    
    if ($recover == $model->recover)
    {
     
    $table = User::findOne(["email" => $model->email, "id" => $id_recover, "verification_code" => $model->verification_code]);
	//if(!empty($model->password))
    $table->password = $model->password;
	 //$table->password = crypt($model->password, Yii::$app->params['salt']);
	 
     if ($table->save(false))
     {
      
      
      $session->destroy();
      
      //Vaciar los campos del formulario
      $model->email = null;
      $model->password = null;
      $model->password_repeat = null;
      $model->recover = null;
      $model->verification_code = null;
      
     Yii::$app->session->setFlash('successNewpass','הסיסמא שונתה בהצלחה!');
	 return $this->redirect(['/site/login']);
      //$msg .= "<meta http-equiv='refresh' content='5; ".Url::toRoute("site/login")."'>";
     }
     else
     {
      $msg = '<div class="alert alert-success alert-dismissable">שגיאה!
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>';
     }
     
    }
    else
    {
     $model->getErrors();
    }
   }
  }
  
  return $this->render("resetpass", ["model" => $model, "msg" => $msg]);
  
 }

	
	
	
	
/////////////////////////////////////////////////////////////////////////////
	
	

    public function actionIndex()
    {
        return $this->render('index');
    }

	
	 
	 
	 
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->homeUrl = ['site/index'];	
		Yii::$app->user->logout();

		return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'מי אנחנו';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
	<h2 style="font-family:Copperplate Gothic Light;
	
	font-style: italic;
	font-variant: small-caps;
	font-weight: bold;
	line-height: 45.1px;
		
		font-size: 500%;color: #420b3a;"><b> Webni.co.il</h2>
    <div style = "font-size:20px;"><p>
   אנו צוות פיתוח אתרים ומערכות מידע אשר הוקם בשנת 2016
    </p>
 <p>
  הצוות הוקם על ידי שני סטודנטים להנדסת תעשייה וניהול - מערכות מידע, אלירז שמעון וליעד ניזרי.
    </p>
	 <p>
  החזון שלנו הינו לפתח ולשרת קהל רב של ארגונים ועסקים תוך מתן פתרונות תוכנה לייעול העבודה השוטפת וקידום בית העסק או הארגון.
    </p>
	 <p>
אנו מתמקדים בפיתוח סביבות עבודה נוחות ופשוטות אשר יקלו על משתמשי הקצה באשר הם ולכל אדם תהיה היכולת להפעיל את המערכות שלנו.    </p>
   <!-- <code><?//= __FILE__ ?></code>-->
</div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/eventdelete.php
<?php
use yii\helpers\Html;
?>

<div class="username">
  www
</div>

views/site/index.php
<?php
use yii\imagine\Image;

/* @var $this yii\web\View */

$this->title = 'Prat.Webni';
?>
<div class="site-index">
	<?php if (Yii::$app->session->hasFlash('success')): ?>
  <div class="alert alert-success alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
 
  <?= Yii::$app->session->getFlash('success') ?>
  </div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('successPmail')): ?>
  <div class="alert alert-success alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
 
  <?= Yii::$app->session->getFlash('successPmail') ?>
  </div>
<?php endif; ?>

<?php if (Yii::$app->session->hasFlash('successNewpass')): ?>
  <div class="alert alert-success alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
 
  <?= Yii::$app->session->getFlash('successNewpass') ?>
  </div>
<?php endif; ?>
    <div class="jumbotron">
        <h1 style = "margin-top:1%; color: #420b3a
;
		
		font-family:Copperplate Gothic Light;
	
	font-style: italic;
	font-variant: small-caps;
	font-weight: bold;
	line-height: 45.1px;
		
		font-size: 200%;
		
		"> Prat.Webni.Co.Il </h1>
<?php 	if(Yii::$app->user->isGuest){?>
        <p class="lead" style = " color: #420b3a
">ברוכים הבאים למערכת ניהול שמורת הטבע עין פרת</p>
		        <p><a class="btn btn-lg btn-success" href="http://prat.webni.co.il/app/web/site/login">כניסה למערכת</a></p>
<?php
}
?>
<?php 	if(!\Yii::$app->user->isGuest){?>
        <p class="lead" style = 
		
		
		"font-family: TimesNewRoman;
	font-size: 40px;
	font-style: italic;
	font-variant: normal;
	font-weight: bold;
	line-height: 44px;
	color: #420b3a;">ברוכים הבאים למערכת ניהול שמורת הטבע עין פרת</p>
		        

				 			

<?php
}
?>
<!--
       <p style = "margin:5%"><a class="btn btn-lg btn-success" href="employees">עובדים</a></p>
		        <p style = "margin:3%"><a class="btn btn-lg btn-success" href="buroc">בירוקרטיה</a></p>
		 
		<img src = "tamar" style="width:304px;height:228px;"></img>
	-->
    </div>
<div>
			<script src="<?= Yii::$app->request->baseUrl?>/js/jssor.slider-21.1.6.min.js" type="text/javascript"></script>
			<script type="text/javascript">
        jssor_1_slider_init = function() {

            var jssor_1_options = {
              $AutoPlay: true,
              $Idle: 0,
              $AutoPlaySteps: 2,
              $SlideDuration: 3400,
              $SlideEasing: $Jease$.$Linear,
              $PauseOnHover: 4,
              $SlideWidth: 280,
			  $SlideHeight: 280,
              $Cols: 5,
			  $SlideSpacing: 40,
            };

            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

            /*responsive code begin*/
            /*you can remove responsive code if you don't want the slider scales while window resizing*/
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 809);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $Jssor$.$AddEvent(window, "load", ScaleSlider);
            $Jssor$.$AddEvent(window, "resize", ScaleSlider);
            $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
            /*responsive code end*/
        };
    </script>
    <style></style>
    <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 980px; height: 350px; overflow: hidden; visibility: hidden;">
        <!-- Loading Screen -->
        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
            <div style="position:absolute;display:block;background:url('<?= Yii::$app->request->baseUrl?>/img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
        </div>
        <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 980px; height: 280px; overflow: hidden;">
            <div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
                <img data-u="image" src="http://liadni.webni.co.il/%D7%9B%D7%95%D7%A1.jpg" />
            </div>
   <div style="display: none;padding:1px; border:3px solid  #420b3a;
   
   background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;
   
   
   
   
   ">
  



  <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/10.jpg" />
            </div>
           
   <div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
   <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/22.jpg" />
            </div>
              <div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/33.jpg" />
            </div>
            <div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/17.jpg" />
            </div>
              <div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/18.jpg" />
            </div>
            <div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/20.jpg" />
            </div>
              <div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/44.jpg" />
            </div>
			   <div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/5.jpg" />
				 </div>
               <div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/55.jpg" />
            </div> 
			<div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">
                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/6.jpg" />
            </div>
						
						<div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">

                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/77.jpg" />
            </div>
						<div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">

                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/88.jpg" />
            </div>
			 			<div style="display: none;padding:1px; border:3px solid  #420b3a; background-color: #f0f8ff;
-moz-box-shadow: 0px 0px 20px #000000;
-webkit-box-shadow: 0px 0px 20px #000000;
box-shadow: 0px 20px 20px #000000;">

                <img data-u="image" src="<?= Yii::$app->request->baseUrl?>/img/nevia.jpg" />
            </div>
			
			
			
        </div>
    </div>
    <script type="text/javascript">jssor_1_slider_init();</script>
    <!-- #endregion Jssor Slider End -->
		</div>
    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <!--<h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
           --> </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'כניסה';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
<?php if (Yii::$app->session->hasFlash('successNewpass')): ?>
  <div class="alert alert-success alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
 
  <?= Yii::$app->session->getFlash('successNewpass') ?>
  </div>
<?php endif; ?>
    <h1><?= Html::encode($this->title) ?></h1>

    <p>לכניסה למערכת הכנס פרטים מזהים:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>
	<?= Html::a('שכחתי סיסמה?', ['site/recoverpass'], ['class' => 'profile-link']) ?>
        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('כניסה', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

   <!-- <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>-->
</div>

views/site/recoverpass.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
 
<h3><?= $msg ?></h3>
 
<h1>איפוס סיסמה</h1>
<?php $form = ActiveForm::begin([
    'method' => 'post',
    'enableClientValidation' => true,
]);
?>
 
<div class="form-group">
 <?= $form->field($model, "email")->input("email") ?>  
</div>
 
<?= Html::submitButton("שלח", ["class" => "btn btn-primary"]) ?>
 
<?php $form->end() ?>

views/site/resetpass.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
 
<h3><?= $msg ?></h3>
 
<h1>איפוס סיסמה</h1>
<?php $form = ActiveForm::begin([
    'method' => 'post',	
	//'id' => 'test1',
	 //'action' => Url::toRoute(\Yii::$app->request->getPathInfo())
    'enableClientValidation' => true,
]);
?>

<div class="form-group">
 <?= $form->field($model, "email")->input("email") ?>  
</div>
 
<div class="form-group">
 <?= $form->field($model, "password")->input("password") ?>  
</div>
 
<div class="form-group">
 <?= $form->field($model, "password_repeat")->input("password") ?>  
</div>

<div class="form-group">
 <?= $form->field($model, "verification_code")->input("text") ?>  
</div>

<div class="form-group">
 <?= $form->field($model, "recover")->input("hidden")->label(false) ?>  
</div>
 
<?= Html::submitButton("שנה סיסמה", ["class" => "btn btn-primary"]) ?>
 
   <?php ActiveForm::end(); ?>